package icu.junyao.springboot.mapper;

import icu.junyao.springboot.model.Student;

/**
 * 扫描dao接口到spring容器
 * 这样只能把一个mapper加入到容器中 可以在程序入口添加MapperScan注解加入多个mapper
 * @Mapper
 */
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Sun May 23 16:43:38 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Sun May 23 16:43:38 CST 2021
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Sun May 23 16:43:38 CST 2021
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Sun May 23 16:43:38 CST 2021
     */
    Student selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Sun May 23 16:43:38 CST 2021
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Sun May 23 16:43:38 CST 2021
     */
    int updateByPrimaryKey(Student record);
}